apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quickjdr-backend
          env:
            - name: APP_ENV
              value: development
            - name: DB_HOST
              value: database
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: quickjdr
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
          ports:
            - containerPort: 8000